# name: Task reminders

# on:
#   schedule:
#     - cron: "0 18 * * *"
#   workflow_dispatch: 

# jobs:
#   call-api:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Call reminder endpoint
#         run: |
#           curl -X POST https://tasly-backend.onrender.com/api/auth/check
